# Generated by Django 4.2.3 on 2024-10-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_API', '0004_remove_order_order_status_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phonenumber',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
