# Generated by Django 4.2.3 on 2024-11-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_API', '0004_category_created_at_product_promo_video_and_more'),
        ('ecommerce_API', '0006_remove_user_city_remove_user_country_and_more'),
    ]

    operations = [
    ]
