# Generated by Django 4.2.3 on 2024-11-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_API', '0010_productinbill_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingbill',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
