# Generated by Django 4.2.3 on 2024-11-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_API', '0012_alter_productinbill_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('etat', models.CharField(choices=[('ferme', 'Fermé'), ('ouvert', 'Ouvert')], default='ferme', max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='ReturnBill',
        ),
    ]
