# Generated by Django 4.2.3 on 2024-11-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_API', '0013_contact_delete_returnbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='etat',
            field=models.CharField(choices=[('ferme', 'Fermé'), ('ouvert', 'Ouvert')], default='ouvert', max_length=6),
        ),
    ]
