# Generated by Django 4.2.3 on 2024-11-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_API', '0017_fournisseur_alter_buyingbill_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingbill',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_API.fournisseur'),
        ),
    ]
