# Generated by Django 4.2.3 on 2024-11-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_API', '0020_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecarouselsection',
            name='header',
        ),
        migrations.RemoveField(
            model_name='homecarouselsection',
            name='image_desktop',
        ),
        migrations.RemoveField(
            model_name='homecarouselsection',
            name='image_phone',
        ),
        migrations.RemoveField(
            model_name='homecarouselsection',
            name='link',
        ),
        migrations.RemoveField(
            model_name='homecarouselsection',
            name='text',
        ),
        migrations.AddField(
            model_name='homecarouselsection',
            name='dateAjout',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='homecarouselsection',
            name='file',
            field=models.FileField(default='', help_text='Upload an image or video.', upload_to='carousel_files/'),
        ),
        migrations.AddField(
            model_name='homecarouselsection',
            name='title',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
