# Generated by Django 4.2.3 on 2025-01-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_API', '0022_alter_productinorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='produit_images/'),
            preserve_default=False,
        ),
    ]
