# Generated by Django 4.2.3 on 2025-01-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_API', '0023_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(default='', help_text='Upload an image.', upload_to='logo_files/')),
                ('lienFacebook', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('lienInstagram', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('lienTiktok', models.CharField(blank=True, default='', max_length=25, null=True)),
            ],
        ),
    ]
